services:
  - type: web
    name: nominatim
    env: docker
    plan: standard # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: PBF_URL
        value: https://download.geofabrik.de/europe/france-latest.osm.pbf
      - key: REPLICATION_URL
        value: https://download.geofabrik.de/europe/france-updates/
